### ISSUE TITLE
About the infer speed

### ISSUE THREAD

**Issue by KeyKy** [farmingyard/ShuffleNet#3]
I try your deploy.prototox but the infer speed is 0.015s/image (batch-size = 1). While mobilenet (2x of your prototxt, not 1by2) is 0.005s/image. ShuffleNet should run faster than mobilenet according to the original paper.

**Comment by leolee96** [comment]
Hi @KeyKy , I tested them as well. In my case shufflenet(g=1) runs faster than mobilenet (batchsize 128), 0.28s and 0.36s respectively. Yet Shufflenet group = 3 runs slower, 0.39s per iteration. I guess the problem might be caused by the inefficient group computation.

Btw @KeyKy @farmingyard  what's you guys' training acc? I got a rather pool acc performance with the shufflenet both g=1 and g=3. Top1 acc is only around 10% at approximately 200000/450000 iterations.

thanks

**Comment by SophieZhou** [comment]
Using the prototxt file of farmingyard, I got 45% around for top1 acc after 10 epoches.  And it is true with group=3, the speed is slow then mobilenet. I am sure it is because of the group convolution in CAFFE. Because after I convert my mobilenet prototxt from group convolution to depthwiseconvolution, the speed is very fast.

**Comment by KeyKy** [comment]
@SophieZhou It is so weird and probably no sense that group=1 is faster than group=3. Could you share your shuffle(group=1) prototxt with me? For now my shufflenet accuracy is about 60%

**Comment by farmingyard** [comment]
@KeyKy @leolee96 @SophieZhou 
You are right, the original caffe group conv is slow, especially in case of many groups such as depthwise conv, so I recommend you to use the depthwise conv codes but no group conv for mobilenet and shufflenet's depthwise conv layer. But for shufflenet's group(group is small, such as 3) conv(1x1 kernel), I think the specialized optimization codes is helpful. By the way, the shufflenet speed is also include shuffle process, this part is also considerable.
@leolee96 There should be something wrong with you training, in my option the problem may occurs in your solver.prototxt, double check it.

**Comment by farmingyard** [comment]
@KeyKy Your shufflenet's top1 accuracy is about 60%? How many epochs have you trained?

**Comment by KeyKy** [comment]
@farmingyard Yes! The total iterations for now is 1200000 with batch-size = 32. However, it is useless that its infer speed is much slower than mobilenet. Have you check shufflenet(group = 1)? According to @leolee96 it faster than mobilenet.

**Comment by farmingyard** [comment]
@KeyKy Good job! It seems that your nvidia card is not bad,haha~
I have not try shufflenet(group=1) yet, but when the group=1, it no needs shuffle channel process and may faster in our current codes.

**Comment by KeyKy** [comment]
@farmingyard OH! your are right (group=1 needs not shuffle channel). Looking forward to more faster shufflenet. I'm now struggling to implement and transfer the conv_dw to mxnet.

**Comment by farmingyard** [comment]
@KeyKy How is mxnet's depthwise conv? Is it also group+gemm?

**Comment by KeyKy** [comment]
@farmingyard Nope. I use cuda to reimplement it.

**Comment by zimenglan-sysu-512** [comment]
hi @farmingyard have you ever tested the speeds of both normal group conv layer (group is equal to channel) and `ConvolutionDepthwise` layer for deepwise convolution？

**Comment by farmingyard** [comment]
@zimenglan-sysu-512
The caffe's normal group conv layer (group is equal to channel) is very slower than this depthwise conv, and some specialized optimization codes of dw conv is more efficient.
